### ISSUE TITLE
Check the maximum length of fields

### ISSUE THREAD

**Issue by Daanvm** [php-twinfield/twinfield#16]
It would be nice if we would check the max length of fields before sending it to Twinfield. Twinfield returns an error if a field is too long.

We could either throw an exception as soon as the field is set, or we could truncate the fields before adding it to the XML file. I personally think that throwing an exception is preferable.

**Comment by willemstuursma** [comment]
We could use Symfony's validator and add annotations to fields, use that.

**Comment by Thijs-Riezebeek** [comment]
I'd prefer not to start adding Symfony's validator, requiring meta programming, just so we don't have to write an `if (strlen($value) > 40)`. The tests need to be written either way.

Besides that I'd prefer truncation over exceptions. For our use case we will be truncating everything.

Since I can see the benefit of having methods that throw an exception as well, I'd suggest adding two separate methods for this (no boolean parameters, please 🙏 ).

**Comment by remcotolsma** [comment]
I don't think this belongs in this library. If a value is long, Twinfield will warn you with an error message. It's up to users if they want to truncate or throw exceptions.

**Comment by willemstuursma** [comment]
Hey @remcotolsma are you back!
